# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "julia"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    ignore:
      # required for Julia v1.6 runs
      - dependency-name: "julia-actions/julia-downgrade-compat"
        versions: ["<2"]
