[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
KernelDensityEstimation = "e46ec5f4-66dc-4371-a668-81bd92d19d7d"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[sources]
KernelDensityEstimation = {path = ".."}

[compat]
Documenter = "1.3"
DocumenterInterLinks = "1"
KernelDensity = "0.6"
Makie = "0.20, 0.21, 0.22, 0.23, 0.24"
MarkdownAST = "0.1"
Plots = "1"
julia = "1.6"

[extras]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
